// ============================================================
// SUMMON MCP — Deploy Config Tool
// Shape-aware: Claude Project for experts/councils, Paperclip for orgs
// ============================================================

import type { DesignOutput, DeployConfigOutput } from "../types/index.js";
import { generatePaperclipAgentConfig, generateAgentMd, BUDGET_GUIDELINES } from "../templates/paperclip.js";

export function executeDeployConfig(input: {
  architecture: DesignOutput;
  agent_superprompts: Record<string, string>;
}): DeployConfigOutput {
  const shape = input.architecture.architecture.shape;
  const objective = input.architecture.architecture.objective;
  const agents = input.architecture.agents;

  // Determine deployment type based on shape
  const deploymentType: "claude_project" | "paperclip" | "both" =
    shape === "single_expert" ? "claude_project" :
    shape === "council" ? "claude_project" :
    shape === "full_org" ? "paperclip" :
    "both"; // hybrid

  // Generate agents.md files for all agents
  const agentsMdFiles: Record<string, string> = {};
  const companyName = `SUMMON — ${objective}`;
  agents.forEach(agent => {
    agentsMdFiles[agent.id] = generateAgentMd(agent, companyName);
  });

  // Build output based on deployment type
  const output: DeployConfigOutput = {
    deployment_type: deploymentType,
    agents_md_files: agentsMdFiles,
    build_prompt: "",
    deployment_instructions: ""
  };

  // Claude Project config (for experts and councils)
  if (deploymentType === "claude_project" || deploymentType === "both") {
    const allSuperprompts = Object.values(input.agent_superprompts).join("\n\n---\n\n");

    const councilPrefix = shape === "council" && input.architecture.council_config
      ? `COUNCIL ORCHESTRATION:\n${input.architecture.council_config.debate_protocol}\n\nCOUNCIL MEMBERS:\n${agents.map(a => `- ${a.title} (${a.archetype})`).join("\n")}\n\nCONFLICT MAP:\n${input.architecture.council_config.conflict_map.map(c => `- ${c.agent_a} vs ${c.agent_b}: ${c.predicted_fault_line}`).join("\n")}\n\n---\n\n`
      : "";

    output.claude_project_config = {
      system_prompt: councilPrefix + allSuperprompts,
      re_anchoring_prompt: generateReAnchoringPrompt(agents, input.agent_superprompts),
      sample_exchange: `[Sample exchange to be generated by the host LLM after deploying the superprompt. Test with a domain-specific question that requires 3+ layers to answer well.]`,
      refinement_prompts: [
        "Ask a question that tests the expert's domain boundaries — does it flag uncertainty appropriately?",
        "Challenge a core belief — does the expert push back with specific reasoning, not generic defense?",
        "Ask something outside the primary domain — does the expert adjust confidence and reference its Domain Transfer Protocol?"
      ]
    };
  }

  // Paperclip config (for orgs and hybrid)
  if (deploymentType === "paperclip" || deploymentType === "both") {
    const paperclipAgents = agents.map(agent =>
      generatePaperclipAgentConfig(agent, input.agent_superprompts[agent.id] || "SUPERPROMPT NOT YET BUILT")
    );

    output.paperclip_config = {
      company: {
        name: companyName,
        mission: objective
      },
      agents: paperclipAgents,
      org_chart: input.architecture.org_chart as Record<string, unknown>,
      goals: [
        {
          title: "Primary Objective",
          description: objective,
          measurable: true,
          time_boxed: "90 days"
        }
      ]
    };
  }

  // Generate build prompt
  output.build_prompt = generateBuildPrompt(input.architecture, input.agent_superprompts, deploymentType);

  // Generate deployment instructions
  output.deployment_instructions = generateDeploymentInstructions(deploymentType, agents.length);

  return output;
}

function generateReAnchoringPrompt(agents: DesignOutput["agents"], superprompts: Record<string, string>): string {
  if (agents.length === 1) {
    const agent = agents[0]!;
    return `[PERSONA CHECK] You are ${agent.title}. Archetype: ${agent.archetype}. Your primary cognitive lens drives everything. Review your anti-patterns — what do you NEVER do? Check your calibration anchors. The next response should sound unmistakably like your architecture, not generic AI. Continue in character.`;
  }

  return agents.map(agent =>
    `[PERSONA CHECK — ${agent.title}] Archetype: ${agent.archetype}. Core reasoning approach: ${agent.archetype_rationale}. Stay in your lane. The next response uses YOUR mental models, not generic reasoning.`
  ).join("\n\n");
}

function generateBuildPrompt(architecture: DesignOutput, superprompts: Record<string, string>, deploymentType: string): string {
  if (deploymentType === "claude_project") {
    return `DEPLOYMENT: Claude.ai Project

1. Create a new Claude.ai Project
2. Paste the system_prompt into the Project's Custom Instructions
3. Upload any relevant domain documents as Project files
4. Enable web search if the expert should access current information
5. Test with a domain-specific question
6. Use the re-anchoring prompt at turn 10-15 and every 10-15 turns thereafter`;
  }

  const agentList = architecture.agents.map(a => a.id).join(", ");

  return `DEPLOYMENT: Paperclip via Claude Code

You are deploying a Paperclip company: "${architecture.architecture.objective}"

SETUP SEQUENCE:
1. Ensure Paperclip is installed: npx paperclipai onboard --yes
2. Create the company in the Paperclip dashboard
3. Set the mission to: "${architecture.architecture.objective}"
4. Create agents: ${agentList}
5. For each agent, create their agents.md file in ./agents/
6. Configure heartbeats, budgets, and reporting lines per the config
7. Launch via start.sh (NEVER from Claude Code terminal)
8. Day 1: OBSERVE ONLY. Do not optimize.
9. Day 2: Tune heartbeat intervals based on observed patterns
10. Week 1: Experiment with task assignment and review governance gates

CRITICAL REMINDERS:
- All budgets are non-zero (zero = unlimited = runaway risk)
- All heartbeats are >= 30 seconds
- Launch via start.sh, not from Claude Code terminal
- Run \`pnpm paperclipai doctor --repair\` before first launch`;
}

function generateDeploymentInstructions(deploymentType: string, agentCount: number): string {
  if (deploymentType === "claude_project") {
    return `DEPLOYMENT INSTRUCTIONS:
1. Copy the system_prompt from claude_project_config
2. Create a new Claude.ai Project
3. Paste into Custom Instructions
4. Upload relevant domain documents as Project files
5. Start a conversation — the expert/council is live
6. Use the re-anchoring prompt every 10-15 turns to maintain character

ESTIMATED SETUP TIME: 5 minutes`;
  }

  return `DEPLOYMENT INSTRUCTIONS:
1. Ensure Paperclip is installed and running
2. Use the build_prompt with Claude Code to deploy automatically
   OR manually create the company and agents in the Paperclip dashboard
3. Copy each agent's superprompt into their agents.md file
4. Configure heartbeats, budgets, and org chart per the paperclip_config
5. Run: pnpm paperclipai doctor --repair
6. Launch via start.sh
7. Day 1: Observe only — watch agent behavior, check triage inbox
8. Day 2: Tune heartbeat intervals
9. Week 1: Iterate on agent prompts based on output quality

ESTIMATED SETUP TIME: ${agentCount <= 5 ? "15-30 minutes" : "30-60 minutes"}
ESTIMATED MONTHLY COST: $${(agentCount * 25).toFixed(0)}-$${(agentCount * 50).toFixed(0)} (varies by model and heartbeat frequency)`;
}
